name: Python Workflow

on:
  push:
    branches:
      - main  # Executa o workflow quando houver um push no branch 'main'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Alterar para a versão desejada

      # Instala dependências (caso tenha um requirements.txt)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Executa o script Python
      - name: Run Python script
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "Usando o secret: $TOKEN"
          python hello-world.py
